### PR TITLE
fix: smear on zz zt zb movements

### LINKED ISSUE #62: No smear on `zt`, `zz`, or `zb` with `scroll_buffer_space = true`
The smear does not appear on `zt`, `zz`, or `zb` movements when `scroll_buffer_space = true`. It appears correctly when `scroll_buffer_space = false`.

## Environment

- Neovim version: v0.10.2
- Smear-cursor version/commit: [f0f1e41](https://github.com/sphamba/smear-cursor.nvim/commit/f0f1e41bbfefd6904fe399ba07328f5073bcd42c)

### PR DESCRIPTION
**Pull request by sphamba**
Show smear on `zz`, `zt` and `zb` movements even when `smear_buffer_space` is set to `true` by checking if the current line has changed or not.

## Related GitHub issues and pull requests

- fix #62

### CODE REVIEW

File: lua/smear_cursor/animation.lua [hunk 1]
```diff
@@ -231,7 +235,7 @@ local function clamp_to_buffer(position)
 end
 
 local function scroll_buffer_space()
-	if current_top_row ~= previous_top_row then
+	if current_top_row ~= previous_top_row and current_line ~= previous_line then
```
Comment (bew) [inline lua/smear_cursor/animation.lua:238]: I don't understand the change though 🤔

Why tracking for the line nr in the buffer and doing something when it's different has any behavior change when the line nr don't actually change with `z*` actions?

Comment (sphamba) [reply lua/smear_cursor/animation.lua:238]: The `scroll_buffer_space` function shifts the smear's origin (in screen space) before drawing it, to take the buffer's scroll into account. This is only needed when doing `<c-u>` or `<c-d>` (`current_top_row ~= previous_top_row` and `current_line ~= previous_line`).

This PR prevents the shift for `z*` movements (`current_top_row ~= previous_top_row` and **`current_line == previous_line`**).
